title: Boom Diggity
author: Jerry O
theme: minima
email: jerry.oliver@lexisnexisrisk.com
description: > # this means to ignore newlines until "baseurl:"
  Just a test site for training purposes. Enjoy

# social links
twitter_username: JerryO # DO NOT include the @ character, or else the build will fail!
github_username:  Olivje01 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
